services:
  # Caddy Reverse Proxy with IP (no SSL)
  caddy:
    image: caddy:2-alpine
    container_name: stoplist-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_logs:/var/log/caddy
    networks:
      - stoplist-network
    depends_on:
      - stoplist-frontend
      - stoplist-backend

  # PostgreSQL Database
  postgres:
    image: postgis/postgis:15-3.3
    container_name: stoplist-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: stoplist_db
      POSTGRES_USER: stoplist_user
      POSTGRES_PASSWORD: stoplist_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ../pcl-backend/src/migrations:/docker-entrypoint-initdb.d
    networks:
      - stoplist-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stoplist_user -d stoplist_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  # Backend API Service
  stoplist-backend:
    build:
      context: ../pcl-backend
      dockerfile: Dockerfile
    container_name: stoplist-backend
    ports:
      - "3836:3837"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: stoplist_user
      DB_PASSWORD: stoplist_password
      DB_DATABASE: stoplist_db
      JWT_SECRET_KEY: stoplist-jwt-secret-key
      JWT_EXPIRATION_TIME: 24h
      APP_PORT: 3837
    networks:
      - stoplist-network
    depends_on:
      postgres:
        condition: service_healthy

  # Frontend Service
  stoplist-frontend:
    build:
      context: ../pcl-frontend
      dockerfile: Dockerfile
    container_name: stoplist-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://172.17.128.147:3836/v1/api
    ports:
      - "3000:3000"
    networks:
      - stoplist-network

networks:
  stoplist-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  caddy_logs:
    driver: local
